### ISSUE TITLE
How to Extract Features Using LLaMAGen

### ISSUE THREAD

**Issue by ziqipang** [haoosz/BiGR#1]
@haoosz Thanks for the amazing work! I have a question about how you extracted the features using LLaMAGen? For instance, do you directly apply the causal attention to the tokens one-by-one, then apply the same average pooling? Thank you so much!

**Comment by haoosz** [comment]
Hi @ziqipang , thanks for your interest in our work!

We input all tokens of an image into LlamaGen, which operates using standard causal attention, and apply the same average pooling at the same transformer layer.

**Comment by ziqipang** [comment]
Thanks
